github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true

image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      cp .env.template .env
    command: >
      sudo service cron start &&
      gp sync-done variables
    name: Init .env file
  - command: >
      aws configure set region eu-central-1
    name: Init AWS config
  - init: >
      git submodule update --init --remote &&
      cd services/forward-proxy &&
      git checkout master &&
      cd /workspace/stack/drupal/docroot &&
      git submodule update --init --remote &&
      cd config/content-sync &&
      git checkout master &&
      cd /workspace/stack/drupal/docroot/docroot/sites &&
      git checkout master
    command: >
      gp sync-done submodules-prepare
    name: Prepare all submodules