github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: true

image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      cp .env.template .env
    command: >
      sudo service cron start &&
      gp sync-done variables
    name: Init .env file
  - command: >
      aws configure set region eu-central-1
    name: Init AWS config