#!/bin/bash

APP_DOMAIN=$(gp url 3000)
export APP_DOMAIN=${APP_DOMAIN:8}

EMBED_DOMAIN=$(gp url 3001)
export EMBED_DOMAIN=${EMBED_DOMAIN:8}

API_DOMAIN=$(gp url 3010)
export API_DOMAIN=${API_DOMAIN:8}

SYNC_CORE_DOMAIN=$(gp url 3020)
export SYNC_CORE_DOMAIN=${SYNC_CORE_DOMAIN:8}

# Elastic & Kibana
ELASTICSEARCH_DOMAIN=$(gp url 9200)
export ELASTICSEARCH_DOMAIN=${ELASTICSEARCH_DOMAIN:8}
KIBANA_DOMAIN=$(gp url 5601)
export KIBANA_DOMAIN=${KIBANA_DOMAIN:8}

# Drupal
DEFAULT_EXPORT_DOMAIN=$(gp url 3030)
export DEFAULT_EXPORT_DOMAIN=${DEFAULT_EXPORT_DOMAIN:8}
DEFAULT_IMPORT_DOMAIN=$(gp url 3031)
export DEFAULT_IMPORT_DOMAIN=${DEFAULT_IMPORT_DOMAIN:8}
SYNDICATION_SITE_1_DOMAIN=$(gp url 3032)
export SYNDICATION_SITE_1_DOMAIN=${SYNDICATION_SITE_1_DOMAIN:8}
SYNDICATION_SITE_2_DOMAIN=$(gp url 3033)
export SYNDICATION_SITE_2_DOMAIN=${SYNDICATION_SITE_2_DOMAIN:8}
SYNDICATION_SITE_3_DOMAIN=$(gp url 3034)
export SYNDICATION_SITE_3_DOMAIN=${SYNDICATION_SITE_3_DOMAIN:8}
FRESH_EXPORT_DOMAIN=$(gp url 3035)
export FRESH_EXPORT_DOMAIN=${FRESH_EXPORT_DOMAIN:8}
FRESH_IMPORT_DOMAIN=$(gp url 3036)
export FRESH_IMPORT_DOMAIN=${FRESH_IMPORT_DOMAIN:8}

# Wordpress
DEFAULT_WORDPRESS_EXPORT_DOMAIN=$(gp url 3050)
export DEFAULT_WORDPRESS_EXPORT_DOMAIN=${DEFAULT_WORDPRESS_EXPORT_DOMAIN:8}
DEFAULT_WORDPRESS_IMPORT_DOMAIN=$(gp url 3051)
export DEFAULT_WORDPRESS_IMPORT_DOMAIN=${DEFAULT_WORDPRESS_IMPORT_DOMAIN:8}

# Proxy
PROXY_DOMAIN=$(gp url 3040)
export PROXY_DOMAIN=${PROXY_DOMAIN:8}

# Environment variables
ENVIRONMENT_ID=$(git config user.name | tr 'ü' 'ue')
ENVIRONMENT_ID=${ENVIRONMENT_ID//[^a-z0-9A-Z]/-}
export ENVIRONMENT_ID=$(echo "$ENVIRONMENT_ID" | tr '[:upper:]' '[:lower:]')

PUBLIC_HOST_IP=$(hostname -I)
export PUBLIC_HOST_IP=$(echo "${PUBLIC_HOST_IP}" | tr -d '[:space:]')

export PATH=/workspace/stack/scripts/drupal:$PATH

# APIs
if [[ -z "$SENDGRID_API_KEY" ]];
then
  export SENDGRID_API_KEY=""
fi

if [[ -z "$AUTH0_MANAGEMENT_CLIENT_SECRET" ]];
then
  export AUTH0_MANAGEMENT_CLIENT_SECRET=""
fi

if [[ -z "$HUBSPOT_API_KEY" ]];
then
  export HUBSPOT_API_KEY=""
fi

if [[ -z "$STRIPE_SECRET_API_KEY" ]];
then
  export STRIPE_SECRET_API_KEY=""
  export ENABLE_STRIPE_INTEGRATION="false"
else
  export ENABLE_STRIPE_INTEGRATION="true"
fi
if [[ -z "$STRIPE_WEBHOOK_SECRET" ]];
then
  export STRIPE_WEBHOOK_SECRET=""
fi

if [[ -z "$XERO_CLIENT_ID" ]];
then
  export XERO_CLIENT_ID=""
fi
if [[ -z "$XERO_CLIENT_SECRET" ]];
then
  export XERO_CLIENT_SECRET=""
  export ENABLE_XERO_INTEGRATION="false"
else
  export ENABLE_XERO_INTEGRATION="true"
fi

# Check for Drupal and Content Sync Version
if [[ -z "$DRUPAL_VERSION" ]];
then
  export DRUPAL_VERSION="8"
fi
if [[ -z "$CONTENT_SYNC_VERSION" ]];
then
  export CONTENT_SYNC_VERSION="2"
fi
